import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@radix-ui/react-label";
import { Input } from "@/components/ui/input";
import { ChevronRight } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       ></body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Card className="w-full max-w-sm">
            <CardHeader>
              {" "}
              <SignedOut></SignedOut>
              <CardTitle className="flex justify-center font-bold">
                Sign in to test
              </CardTitle>
              <CardDescription className="flex justify-center">
                Welcome back! Please sign in to continue
              </CardDescription>
            </CardHeader>

            <CardContent>
              <form>
                <div className="flex flex-col gap-6">
                  <div className="grid gap-2">
                    <SignedIn>
                      <Button variant="outline" className="w-full">
                        <img className="w-4" src="./googleIcon.png" /> Continue
                        with Google
                      </Button>
                    </SignedIn>
                    <Label htmlFor="email">Email</Label>
                    <Input
                      id="email"
                      type="email"
                      placeholder="Enter your email address"
                      required
                    />
                  </div>
                </div>
              </form>
            </CardContent>
            <CardFooter className="flex-col gap-2">
              <Button type="submit" className="w-full bg-purple-600">
                <SignInButton />
              </Button>

              <CardAction className="flex justify-center items-center w-full">
                <p className="text-neutral-500 text-sm">
                  Don't have an account?
                </p>
                <Button className="text-purple-600" variant="link">
                  <SignUpButton>Sign Up</SignUpButton>
                </Button>
              </CardAction>
            </CardFooter>
          </Card>

          <SidebarProvider style={{}}>{children}</SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
